spring:
  application:
    name: pixelmate


server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /
    session:
      timeout: 5m
  

com:
  tomcvt:
    pixelmate:
      security:
        enabled: false

pixelmate:
  cache-dir: cached-data
  img-constraints:
    max-width: 1920
    max-height: 1920
    max-pixels: 2073600 # 1920x1080
    size-limit-bytes: 8294400
  limits:
    active-pipelines: 10
    memory-usage-mb: 360 # img limit x 3 (approx per running pipeline) x 1.5 (overhead) x working pipelines (10)