spring:
  application:
    name: pixelmate


server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /
    session:
      timeout: 5m
  

com:
  tomcvt:
    pixelmate:
      security:
        enabled: false

pixelmate:
  cache-dir: cached-data